import type { Metadata } from "next";
import { Darumadrop_One, Judson } from "next/font/google";
import Sidebar from "@/components/sidebar";
import "./globals.css";

const darumadropOne = Darumadrop_One({
  variable: "--heading-font-raw",
  subsets: ["latin"],
  weight: "400",
});

const judson = Judson({
  variable: "--body-font-raw",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${darumadropOne.variable} ${judson.variable} h-full antialiased`}
    >
      <body className="bg-brand-pink min-h-screen flex relative overflow-x-hidden">
      <Sidebar />
        <main
        className="ml-24 flex-1 min-w-0 p-8 min-h-screen">
        {children}
        </main>
        </body>
    </html>
  );
}
